# Generated by Django 4.1.5 on 2023-01-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
