# Generated by Django 4.1.5 on 2023-01-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_leave_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='total_leave',
        ),
    ]
