# Generated by Django 4.1.5 on 2023-01-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_leave_reason_alter_leave_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='end_leave_enddate',
            new_name='enddate',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='remaining_leave',
            new_name='remainingleave',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='start_leave_date',
            new_name='startdate',
        ),
    ]
