# Generated by Django 4.1.5 on 2023-01-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_rename_end_leave_enddate_leave_enddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='user',
        ),
    ]
