# Generated by Django 4.1.5 on 2023-01-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_leave_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='remainingleave',
            field=models.IntegerField(null=True),
        ),
    ]
