# Generated by Django 4.1.5 on 2023-01-27 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_leave_remainingleave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='enddate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='remainingleave',
            new_name='remaining_leave',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='startdate',
            new_name='start_date',
        ),
    ]
