# Generated by Django 4.1.5 on 2023-01-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_leave_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='user',
            field=models.EmailField(editable=False, max_length=254, null=True),
        ),
    ]
